# Generated by Django 2.1 on 2019-06-08 17:05

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gigs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='dateTime',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date posted'),
        ),
    ]
