# Generated by Django 2.1 on 2019-06-14 12:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('gigs', '0002_auto_20190608_1705'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='gig',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artist', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='attendance',
            name='gig',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gigs.Gig'),
        ),
        migrations.AddField(
            model_name='gig',
            name='attendees',
            field=models.ManyToManyField(through='gigs.Attendance', to=settings.AUTH_USER_MODEL),
        ),
    ]
